spring.application.name=codebasearchaeologist

spring.datasource.url=jdbc:postgresql://localhost:5432/codebase_archaeologist
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
